# Generated by Django 2.2.6 on 2020-08-28 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0007_auto_20200828_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='books',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publisher_book', to='p_library.Book', verbose_name='Издатель'),
        ),
    ]
