# Generated by Django 2.2.6 on 2020-08-28 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0008_publisher_books'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='books',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publisher_book', to='p_library.Book', verbose_name='Книги'),
        ),
    ]
